"""Notebook-facing package for the 2PF to HCR staged pipeline.

This module intentionally resolves exports lazily. Windows native dependencies
such as torch/cellpose are sensitive to import order with the broader
scientific stack, so importing a small stage API should not eagerly import the
entire package tree.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_EXPORT_TO_MODULE = {
    "AnatomyNormalizationStageConfig": "context",
    "AnatomyUint8PreprocessingConfig": "context",
    "ContextStageConfig": "context",
    "FinalFishAuditConfig": "context",
    "FunctionalOrientationStageConfig": "context",
    "FishContext": "context",
    "FishStateStageConfig": "context",
    "VoxelStageConfig": "context",
    "build_context_audit_stage": "context",
    "build_final_fish_audit_stage": "context",
    "build_fish_state_audit_df": "context",
    "normalize_anatomy_stack_stage": "context",
    "preprocess_anatomy_uint8_stage": "context",
    "build_registration_helper_stage": "context",
    "build_run_config_stage": "context",
    "build_voxel_debug_stage": "context",
    "first_match": "context",
    "func_orientation_effective": "context",
    "func_orientation_mode": "context",
    "func_polarity_north": "context",
    "infer_anat_labels_path": "context",
    "infer_func_labels_path": "context",
    "infer_hcr_label_paths": "context",
    "infer_hcr_stack_path": "context",
    "infer_hcr_stack_paths": "context",
    "prepare_notebook_paths": "context",
    "normalize_run_config": "context",
    "notebook_bindings_from_context": "context",
    "orient_functional_stacks_stage": "context",
    "require_fish_state": "context",
    "reset_fish_state": "context",
    "resolve_fish_state_stage": "context",
    "resolve_func_polarity": "context",
    "resolve_fish_context": "context",
    "resolve_notebook_context_stage": "context",
    "resolve_voxel_context_stage": "context",
    "scanimage_um_per_px_from_artist": "context",
    "CohortBuildConfig": "cohort",
    "build_cohort_outputs_stage": "cohort",
    "cohort_cache_paths": "cohort",
    "count_trace_genes": "cohort",
    "load_cohort_analysis_state": "cohort",
    "load_cohort_outputs_from_disk": "cohort",
    "resolve_cohort_context_stage": "cohort",
    "save_cohort_outputs_to_disk": "cohort",
    "CohortSuite2p23cConfig": "cohort_suite2p",
    "aggregate_cohort_23c_trace_means": "cohort_suite2p",
    "build_cohort_suite2p_23c_stage": "cohort_suite2p",
    "build_fish_session_color_map": "cohort_suite2p",
    "cohort_suite2p_23c_cache_paths": "cohort_suite2p",
    "load_cohort_suite2p_23c_outputs_from_disk": "cohort_suite2p",
    "parse_fish_ids_csv": "cohort_suite2p",
    "resolve_cohort_suite2p_23c_fish_dir": "cohort_suite2p",
    "NotebookContractViolation": "notebook_contract",
    "check_notebook_contract": "notebook_contract",
    "find_figure_contract_violations": "notebook_contract",
    "find_top_level_defs": "notebook_contract",
    "ActivityConfig": "activity",
    "build_suite2p_response_seed_table": "activity",
    "build_response_bpi_tables": "activity",
    "prepare_single_fish_bpi_diagnostics_stage": "activity",
    "run_single_fish_cell_50ia_stage": "activity",
    "SingleFishBpiDiagnosticsConfig": "activity",
    "NativeDependencyError": "runtime",
    "build_dependency_preflight_report": "runtime",
    "default_local_root": "runtime",
    "FunctionalAnatomyDebugConfig": "matching",
    "FunctionalRoiIdentityConfig": "matching",
    "HcrActivityExportConfig": "matching",
    "MatchingConfig": "matching",
    "_ensure_uint_labels": "matching",
    "_regionprops_centroids_2d": "matching",
    "build_anat_identity_lookup_df": "matching",
    "build_hcr_mask_fate_df": "matching",
    "build_functional_anatomy_debug_df": "matching",
    "build_functional_anatomy_debug_stage": "matching",
    "build_functional_roi_master_df": "matching",
    "build_hcr_activity_tables": "matching",
    "build_plane_centroid_matches": "matching",
    "compute_centroids": "matching",
    "compute_label_overlap": "matching",
    "hungarian_match": "matching",
    "harmonize_functional_labels_to_anatomy": "matching",
    "idx_to_um": "matching",
    "nearest_neighbor_match": "matching",
    "resample_image": "matching",
    "resample_labels_nn": "matching",
    "resolve_plane_transform": "matching",
    "transform_points_between_spaces": "matching",
    "run_single_fish_cell_44_stage": "matching",
    "run_single_fish_cell_46_stage": "matching",
    "run_single_fish_cell_50_stage": "matching",
    "run_single_fish_cell_50i_stage": "matching",
    "summarize_distances": "matching",
    "summarize_functional_anatomy_geometry_metrics": "matching",
    "gene_from_mask": "matching",
    "FunctionalPlacementConfig": "spatial",
    "FunctionalReferenceConfig": "spatial",
    "InPlaneRegistrationComparisonConfig": "spatial",
    "RegistrationSearchConfig": "spatial",
    "_find_embedded_nrrd_header": "spatial",
    "_infer_voxels_from_open_tiff": "spatial",
    "_infer_voxels_nrrd": "spatial",
    "_parse_nrrd_header_text": "spatial",
    "_res_to_um_per_px": "spatial",
    "_to_um": "spatial",
    "apply_func_orientation": "spatial",
    "apply_square_region_mask": "spatial",
    "best_z_by_ncc": "spatial",
    "build_functional_references_stage": "spatial",
    "corrcoef_img": "spatial",
    "imread_any": "spatial",
    "infer_voxels_tiff": "spatial",
    "local_unsharp": "spatial",
    "load_or_cache_voxels": "spatial",
    "ncc_xy": "spatial",
    "norm01": "spatial",
    "registration_metric_from_scores": "spatial",
    "run_in_plane_registration_comparison_stage": "spatial",
    "run_ncc_placement_stage": "spatial",
    "run_registration_search_stage": "spatial",
    "scale_image": "spatial",
    "top_correlated_mean": "spatial",
    "zproject_mean": "spatial",
    "StimulusConfig": "stimulus",
    "build_null_window_start_map": "stimulus",
    "build_prestim_baseline_windows": "stimulus",
    "build_prestim_trial_windows": "stimulus",
    "build_stim_tables": "stimulus",
    "classify_stim_type": "stimulus",
    "combine_segments": "stimulus",
    "compute_zscore_stats": "stimulus",
    "resolve_presented_stimulus_metadata": "stimulus",
    "resolve_stimulus_context": "stimulus",
    "SmokeValidationError": "smoke",
    "run_smoke_tier": "smoke",
    "Suite2pStageConfig": "suite2p",
    "Suite2pStimulusLockedDiagnosticConfig": "suite2p",
    "build_suite2p_stimulus_locked_diagnostic": "suite2p",
    "infer_frame_rate_from_detail": "suite2p",
    "load_suite2p_stage": "suite2p",
    "load_suite2p_dff_map": "suite2p",
    "run_suite2p_stimulus_locked_diagnostic_stage": "suite2p",
    "MotionAucPlotConfig": "traces",
    "annotate_midline_side": "traces",
    "build_single_fish_motion_auc_plot_tables": "traces",
    "TraceExportConfig": "traces",
    "extract_window_with_padding": "traces",
    "export_suite2p_trace_metadata": "traces",
    "filter_high_confidence_pairs": "traces",
    "load_midline_context": "traces",
    "prepare_pairs_for_unique_cells": "traces",
    "resolve_conf_func_csv_analysis": "traces",
    "run_single_fish_cell_51_stage": "traces",
    "AnatomyCellposeConfig": "segmentation",
    "HcrCellposeConfig": "segmentation",
    "collect_hcr_intensity_stack_paths": "segmentation",
    "deduplicate_hcr_intensity_targets": "segmentation",
    "export_suite2p_native_labels_stage": "segmentation",
    "resolve_functional_labels_for_plane": "segmentation",
    "resolve_hcr_cellpose_model_path": "segmentation",
    "resolve_native_suite2p_labels_for_plane": "segmentation",
    "run_anatomy_cellpose_stage": "segmentation",
    "run_hcr_cellpose_stage": "segmentation",
    "run_hcr_external_bigwarp_intensity_stage": "hcr_warp",
    "run_hcr_external_bigwarp_label_stage": "hcr_warp",
    "run_single_fish_cell_38_stage": "hcr_warp",
    "run_single_fish_cell_40_stage": "hcr_warp",
    "run_single_fish_cell_41_stage": "hcr_warp",
    "organize": "organize",
    "collect_cohort_53a_tables": "plots.qa",
    "compute_anatomy_median_xy_radius_um": "plots.qa",
    "render_cohort_53a_summary": "plots.qa",
    "render_single_fish_hcr_anatomy_coexpression_summary": "plots.qa",
    "run_single_fish_cell_22c_stage": "plots.qa",
    "run_single_fish_cell_30_stage": "plots.qa",
    "run_single_fish_cell_34c_stage": "plots.qa",
    "run_single_fish_cell_47_stage": "plots.qa",
    "run_single_fish_cell_47b_stage": "plots.qa",
    "run_single_fish_cell_50f_stage": "plots.qa",
    "run_single_fish_cell_50g_stage": "plots.qa",
    "run_single_fish_cell_53_stage": "plots.qa",
    "run_single_fish_cell_53a_stage": "plots.qa",
    "run_single_fish_cell_54_stage": "plots.qa",
    "run_single_fish_cell_56f_qc_activity_stage": "plots.qa",
    "run_single_fish_cell_56f_qc_stage": "plots.qa",
    "show_ants_registration_region_selector_stage": "plots.qa",
    "show_centroid_match_qa_stage": "plots.qa",
    "show_functional_label_overlay_stage": "plots.qa",
    "show_inplane_registration_method_comparison_stage": "plots.qa",
    "show_regional_match_review_stage": "plots.qa",
    "show_region_shift_square_selector_stage": "plots.qa",
    "show_registration_overlay_stage": "plots.qa",
    "render_cohort_50l_donut_row": "plots.analysis",
    "render_cohort_50l_responsive_identity_donut_row": "plots.analysis",
    "render_cohort_suite2p_23c_full_session_heatmaps": "plots.analysis",
    "render_cohort_suite2p_23c_traces": "plots.analysis",
    "render_single_fish_50l_composite": "plots.analysis",
    "render_single_fish_50l_gene_auc_panel": "plots.analysis",
    "render_single_fish_50l_responsive_identity_donut": "plots.analysis",
    "render_single_fish_50l_bpi_panel": "plots.analysis",
    "render_single_fish_50l_global_auc_panel": "plots.analysis",
    "render_suite2p_full_session_heatmap": "plots.analysis",
    "render_suite2p_stimulus_locked_heatmaps": "plots.analysis",
    "render_suite2p_stimulus_locked_trace_panels": "plots.analysis",
    "render_cohort_56g_diagnostics": "plots.analysis",
    "render_cohort_56h_by_fish": "plots.analysis",
    "render_cohort_56h_status_donut_grid": "plots.analysis",
    "render_cohort_motion_auc": "plots.analysis",
    "run_single_fish_cell_50e_stage": "plots.analysis",
    "run_single_fish_cell_56_stage": "plots.analysis",
    "run_single_fish_cell_56d_stage": "plots.analysis",
    "run_single_fish_cell_56g_stage": "plots.analysis",
    "run_single_fish_cell_56h_stage": "plots.analysis",
    "run_single_fish_cell_57_stage": "plots.analysis",
}

__all__ = [
    "ActivityConfig",
    "AnatomyCellposeConfig",
    "AnatomyNormalizationStageConfig",
    "AnatomyUint8PreprocessingConfig",
    "CohortBuildConfig",
    "CohortSuite2p23cConfig",
    "ContextStageConfig",
    "FishContext",
    "FinalFishAuditConfig",
    "FishStateStageConfig",
    "FunctionalAnatomyDebugConfig",
    "FunctionalPlacementConfig",
    "FunctionalOrientationStageConfig",
    "FunctionalRoiIdentityConfig",
    "FunctionalReferenceConfig",
    "HcrActivityExportConfig",
    "HcrCellposeConfig",
    "InPlaneRegistrationComparisonConfig",
    "MatchingConfig",
    "MotionAucPlotConfig",
    "NativeDependencyError",
    "SingleFishBpiDiagnosticsConfig",
    "NotebookContractViolation",
    "RegistrationSearchConfig",
    "StimulusConfig",
    "TraceExportConfig",
    "SmokeValidationError",
    "Suite2pStageConfig",
    "Suite2pStimulusLockedDiagnosticConfig",
    "VoxelStageConfig",
    "_find_embedded_nrrd_header",
    "_infer_voxels_from_open_tiff",
    "_infer_voxels_nrrd",
    "_parse_nrrd_header_text",
    "_ensure_uint_labels",
    "_regionprops_centroids_2d",
    "_res_to_um_per_px",
    "_to_um",
    "aggregate_cohort_23c_trace_means",
    "annotate_midline_side",
    "apply_func_orientation",
    "apply_square_region_mask",
    "best_z_by_ncc",
    "build_context_audit_stage",
    "build_dependency_preflight_report",
    "build_cohort_outputs_stage",
    "build_cohort_suite2p_23c_stage",
    "build_final_fish_audit_stage",
    "build_anat_identity_lookup_df",
    "build_hcr_mask_fate_df",
    "build_functional_anatomy_debug_df",
    "build_functional_anatomy_debug_stage",
    "build_functional_references_stage",
    "build_functional_roi_master_df",
    "build_fish_state_audit_df",
    "build_fish_session_color_map",
    "build_hcr_activity_tables",
    "build_single_fish_motion_auc_plot_tables",
    "build_plane_centroid_matches",
    "build_voxel_debug_stage",
    "build_null_window_start_map",
    "build_prestim_baseline_windows",
    "build_prestim_trial_windows",
    "build_registration_helper_stage",
    "build_response_bpi_tables",
    "build_suite2p_response_seed_table",
    "build_run_config_stage",
    "build_suite2p_stimulus_locked_diagnostic",
    "prepare_single_fish_bpi_diagnostics_stage",
    "build_stim_tables",
    "check_notebook_contract",
    "classify_stim_type",
    "collect_cohort_53a_tables",
    "compute_anatomy_median_xy_radius_um",
    "cohort_cache_paths",
    "cohort_suite2p_23c_cache_paths",
    "count_trace_genes",
    "combine_segments",
    "compute_centroids",
    "compute_label_overlap",
    "compute_zscore_stats",
    "collect_hcr_intensity_stack_paths",
    "corrcoef_img",
    "deduplicate_hcr_intensity_targets",
    "default_local_root",
    "extract_window_with_padding",
    "export_suite2p_native_labels_stage",
    "export_suite2p_trace_metadata",
    "filter_high_confidence_pairs",
    "find_figure_contract_violations",
    "find_top_level_defs",
    "first_match",
    "func_orientation_effective",
    "func_orientation_mode",
    "func_polarity_north",
    "gene_from_mask",
    "hungarian_match",
    "harmonize_functional_labels_to_anatomy",
    "imread_any",
    "idx_to_um",
    "infer_anat_labels_path",
    "infer_func_labels_path",
    "infer_hcr_label_paths",
    "infer_hcr_stack_path",
    "infer_hcr_stack_paths",
    "infer_voxels_tiff",
    "local_unsharp",
    "load_midline_context",
    "load_suite2p_dff_map",
    "load_suite2p_stage",
    "load_or_cache_voxels",
    "load_cohort_outputs_from_disk",
    "load_cohort_analysis_state",
    "load_cohort_suite2p_23c_outputs_from_disk",
    "ncc_xy",
    "normalize_anatomy_stack_stage",
    "preprocess_anatomy_uint8_stage",
    "normalize_run_config",
    "norm01",
    "notebook_bindings_from_context",
    "orient_functional_stacks_stage",
    "prepare_pairs_for_unique_cells",
    "parse_fish_ids_csv",
    "nearest_neighbor_match",
    "registration_metric_from_scores",
    "render_cohort_53a_summary",
    "render_cohort_50l_donut_row",
    "render_cohort_50l_responsive_identity_donut_row",
    "render_cohort_suite2p_23c_full_session_heatmaps",
    "render_cohort_suite2p_23c_traces",
    "render_single_fish_hcr_anatomy_coexpression_summary",
    "render_single_fish_50l_composite",
    "render_single_fish_50l_responsive_identity_donut",
    "render_single_fish_50l_bpi_panel",
    "render_single_fish_50l_gene_auc_panel",
    "render_single_fish_50l_global_auc_panel",
    "render_suite2p_full_session_heatmap",
    "render_suite2p_stimulus_locked_heatmaps",
    "render_suite2p_stimulus_locked_trace_panels",
    "render_cohort_56g_diagnostics",
    "render_cohort_56h_by_fish",
    "render_cohort_56h_status_donut_grid",
    "render_cohort_motion_auc",
    "resolve_functional_labels_for_plane",
    "resolve_plane_transform",
    "resample_image",
    "resample_labels_nn",
    "transform_points_between_spaces",
    "resolve_conf_func_csv_analysis",
    "resolve_fish_state_stage",
    "resolve_hcr_cellpose_model_path",
    "resolve_native_suite2p_labels_for_plane",
    "resolve_voxel_context_stage",
    "prepare_notebook_paths",
    "require_fish_state",
    "reset_fish_state",
    "resolve_func_polarity",
    "resolve_fish_context",
    "resolve_notebook_context_stage",
    "resolve_presented_stimulus_metadata",
    "resolve_stimulus_context",
    "resolve_cohort_context_stage",
    "resolve_cohort_suite2p_23c_fish_dir",
    "run_anatomy_cellpose_stage",
    "run_hcr_external_bigwarp_intensity_stage",
    "run_hcr_external_bigwarp_label_stage",
    "run_hcr_cellpose_stage",
    "run_in_plane_registration_comparison_stage",
    "run_ncc_placement_stage",
    "run_registration_search_stage",
    "run_single_fish_cell_22c_stage",
    "run_single_fish_cell_30_stage",
    "run_single_fish_cell_34c_stage",
    "run_single_fish_cell_38_stage",
    "run_single_fish_cell_40_stage",
    "run_single_fish_cell_41_stage",
    "run_single_fish_cell_44_stage",
    "run_single_fish_cell_46_stage",
    "run_single_fish_cell_47_stage",
    "run_single_fish_cell_47b_stage",
    "run_single_fish_cell_50_stage",
    "run_single_fish_cell_50i_stage",
    "run_single_fish_cell_50ia_stage",
    "run_single_fish_cell_50e_stage",
    "run_single_fish_cell_50f_stage",
    "run_single_fish_cell_50g_stage",
    "run_single_fish_cell_51_stage",
    "run_single_fish_cell_53_stage",
    "run_single_fish_cell_53a_stage",
    "run_single_fish_cell_54_stage",
    "run_single_fish_cell_56_stage",
    "run_single_fish_cell_56d_stage",
    "run_single_fish_cell_56f_qc_activity_stage",
    "run_single_fish_cell_56f_qc_stage",
    "run_single_fish_cell_56g_stage",
    "run_single_fish_cell_56h_stage",
    "run_single_fish_cell_57_stage",
    "run_suite2p_stimulus_locked_diagnostic_stage",
    "run_smoke_tier",
    "scale_image",
    "save_cohort_outputs_to_disk",
    "scanimage_um_per_px_from_artist",
    "show_centroid_match_qa_stage",
    "show_ants_registration_region_selector_stage",
    "show_functional_label_overlay_stage",
    "show_inplane_registration_method_comparison_stage",
    "show_regional_match_review_stage",
    "show_region_shift_square_selector_stage",
    "show_registration_overlay_stage",
    "summarize_distances",
    "infer_frame_rate_from_detail",
    "top_correlated_mean",
    "zproject_mean",
    "organize",
]


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
