"""Notebook-facing package for the 2PF to HCR staged pipeline."""

from .context import (
    FishContext,
    build_fish_state_audit_df,
    first_match,
    func_orientation_effective,
    func_orientation_mode,
    func_polarity_north,
    infer_anat_labels_path,
    infer_func_labels_path,
    infer_hcr_label_paths,
    infer_hcr_stack_path,
    infer_hcr_stack_paths,
    prepare_notebook_paths,
    normalize_run_config,
    notebook_bindings_from_context,
    require_fish_state,
    reset_fish_state,
    resolve_func_polarity,
    resolve_fish_context,
    scanimage_um_per_px_from_artist,
)
from .matching import MatchingConfig, build_anat_identity_lookup_df, gene_from_mask
from .spatial import (
    _find_embedded_nrrd_header,
    _infer_voxels_from_open_tiff,
    _infer_voxels_nrrd,
    _parse_nrrd_header_text,
    _res_to_um_per_px,
    _to_um,
    apply_func_orientation,
    best_z_by_ncc,
    corrcoef_img,
    imread_any,
    infer_voxels_tiff,
    local_unsharp,
    load_or_cache_voxels,
    norm01,
    top_correlated_mean,
    zproject_mean,
)
from .stimulus import StimulusConfig, build_stim_tables, resolve_stimulus_context

__all__ = [
    "FishContext",
    "MatchingConfig",
    "StimulusConfig",
    "_find_embedded_nrrd_header",
    "_infer_voxels_from_open_tiff",
    "_infer_voxels_nrrd",
    "_parse_nrrd_header_text",
    "_res_to_um_per_px",
    "_to_um",
    "apply_func_orientation",
    "best_z_by_ncc",
    "build_anat_identity_lookup_df",
    "build_fish_state_audit_df",
    "build_stim_tables",
    "corrcoef_img",
    "first_match",
    "func_orientation_effective",
    "func_orientation_mode",
    "func_polarity_north",
    "gene_from_mask",
    "imread_any",
    "infer_anat_labels_path",
    "infer_func_labels_path",
    "infer_hcr_label_paths",
    "infer_hcr_stack_path",
    "infer_hcr_stack_paths",
    "infer_voxels_tiff",
    "local_unsharp",
    "load_or_cache_voxels",
    "normalize_run_config",
    "norm01",
    "notebook_bindings_from_context",
    "prepare_notebook_paths",
    "require_fish_state",
    "reset_fish_state",
    "resolve_func_polarity",
    "resolve_fish_context",
    "resolve_stimulus_context",
    "scanimage_um_per_px_from_artist",
    "top_correlated_mean",
    "zproject_mean",
]
