#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path


NB_PATH = Path("notebooks/singleFish.ipynb")


REPLACEMENTS = {
    "# [4]": [
        "# [4]\n",
        "# --- Paths (auto-discovered) ---\n",
        "from codeants_2pf_hcr import (\n",
        "    first_match as _first_match_impl,\n",
        "    func_orientation_effective,\n",
        "    func_orientation_mode,\n",
        "    func_polarity_north,\n",
        "    notebook_bindings_from_context,\n",
        "    prepare_notebook_paths,\n",
        "    resolve_func_polarity,\n",
        "    resolve_fish_context,\n",
        ")\n",
        "\n",
        "DATA_MODE = 'local'\n",
        "OWNER = 'Matilde'\n",
        "FISH_ID = 'L395_f11'\n",
        "MATCHING_METADATA_CSV_OVERRIDE = None\n",
        "MANIFEST_OUT_OVERRIDE = None\n",
        "CELLPOSE_MODEL_ROOT_OVERRIDE = None\n",
        "ANAT_CP_MODEL_PATH_OVERRIDE = None\n",
        "CP_HCR_MODEL_PATH_OVERRIDE = None\n",
        "\n",
        "CTX = resolve_fish_context(\n",
        "    fish_id=FISH_ID,\n",
        "    owner=OWNER,\n",
        "    data_mode=DATA_MODE,\n",
        "    matching_metadata_csv_override=MATCHING_METADATA_CSV_OVERRIDE,\n",
        "    manifest_out_override=MANIFEST_OUT_OVERRIDE,\n",
        "    cellpose_model_root_override=CELLPOSE_MODEL_ROOT_OVERRIDE,\n",
        "    anat_cp_model_path_override=ANAT_CP_MODEL_PATH_OVERRIDE,\n",
        "    cp_hcr_model_path_override=CP_HCR_MODEL_PATH_OVERRIDE,\n",
        ")\n",
        "globals().update(notebook_bindings_from_context(CTX))\n",
        "RUN_CONFIG = dict(CTX.run_config)\n",
        "PATHS = prepare_notebook_paths(CTX)\n",
        "globals().update(PATHS)\n",
        "FUNC_STACK_PATH = FUNC_RAW_STACK_PATH\n",
        "def _resolve_func_polarity(force_refresh=False):\n",
        "    global POLARITY, POLARITY_SOURCE, POLARITY_NORTH\n",
        "    if force_refresh or ('POLARITY' not in globals()):\n",
        "        POLARITY, POLARITY_SOURCE = resolve_func_polarity(\n",
        "            FISH_ID,\n",
        "            MATCHING_METADATA_CSV,\n",
        "            polarity_override=POLARITY_OVERRIDE,\n",
        "        )\n",
        "        POLARITY_NORTH = func_polarity_north(POLARITY)\n",
        "    return POLARITY\n",
        "POLARITY = _resolve_func_polarity(force_refresh=True)\n",
        "def first_match(globs, desc, all_hits=False):\n",
        "    del desc\n",
        "    return _first_match_impl(FISH_DIR, globs, all_hits=all_hits)\n",
        "def _func_polarity_north(force_refresh=False):\n",
        "    del force_refresh\n",
        "    return func_polarity_north(POLARITY)\n",
        "def _func_orientation_mode(force_refresh=False):\n",
        "    del force_refresh\n",
        "    return func_orientation_mode(POLARITY)\n",
        "def _func_orientation_effective(force_refresh=False):\n",
        "    del force_refresh\n",
        "    return func_orientation_effective(POLARITY)\n",
        "\n",
        "print(f'[Paths] DATA_MODE={DATA_MODE} DATA_ROOT={DATA_ROOT}')\n",
        "print(f'[Paths] POLARITY={POLARITY} (source={POLARITY_SOURCE})')\n",
        "print(f'[Paths] MATCHING_METADATA_CSV={MATCHING_METADATA_CSV}')\n",
        "print(f'[Paths] MANIFEST_OUT={MANIFEST_OUT}')\n",
        "print(f'[Paths] CELLPOSE_MODEL_ROOT={CELLPOSE_MODEL_ROOT}')\n",
        "print(f'[Paths] ANAT_CP_MODEL_PATH={ANAT_CP_MODEL_PATH}')\n",
        "print(f'[Paths] CP_HCR_MODEL_PATH={CP_HCR_MODEL_PATH}')\n",
    ],
    "# [4a]": [
        "# [4a]\n",
        "from codeants_2pf_hcr import require_fish_state as _require_fish_state_impl, reset_fish_state as _reset_fish_state_impl\n",
        "\n",
        "try:\n",
        "    STATE_FISH_ID\n",
        "except NameError:\n",
        "    STATE_FISH_ID = None\n",
        "\n",
        "RESET_FISH_STATE_ALWAYS = True\n",
        "def reset_fish_state(force=False, verbose=True):\n",
        "    global STATE_FISH_ID\n",
        "    STATE_FISH_ID = _reset_fish_state_impl(STATE_FISH_ID, FISH_ID, force=force)\n",
        "    if verbose:\n",
        "        print(f'[state] Set fish state marker to {STATE_FISH_ID}')\n",
        "    return STATE_FISH_ID\n",
        "\n",
        "def require_fish_state(verbose=True):\n",
        "    ok = _require_fish_state_impl(STATE_FISH_ID, FISH_ID)\n",
        "    if (not ok) and verbose:\n",
        "        print(f'[state] Fish ID changed (state={STATE_FISH_ID}, current={FISH_ID}). Run cell [4a] and upstream cells.')\n",
        "    return ok\n",
        "\n",
        "STATE_FISH_ID = reset_fish_state(force=RESET_FISH_STATE_ALWAYS, verbose=True)\n",
        "if RESET_FISH_STATE_ALWAYS:\n",
        "    print('[state] RESET_FISH_STATE_ALWAYS=True (fish marker refreshed on every run)')\n",
    ],
    "# [4b]": [
        "# [4b]\n",
        "from codeants_2pf_hcr import normalize_run_config\n",
        "\n",
        "_BASE_RUN_CONFIG = dict(CTX.run_config) if 'CTX' in globals() else {}\n",
        "try:\n",
        "    _USER_RUN_CONFIG = RUN_CONFIG if isinstance(RUN_CONFIG, dict) else {}\n",
        "except NameError:\n",
        "    _USER_RUN_CONFIG = {}\n",
        "RUN_CONFIG = normalize_run_config({**_BASE_RUN_CONFIG, **_USER_RUN_CONFIG})\n",
        "HIGH_CONF_ONLY = RUN_CONFIG['HIGH_CONF_ONLY']\n",
        "SKIP_47 = RUN_CONFIG['SKIP_47']\n",
        "STIM_ONSET_DELAY_SEC = RUN_CONFIG['STIM_ONSET_DELAY_SEC']\n",
        "TARGET_STIM_TYPES = RUN_CONFIG['TARGET_STIM_TYPES']\n",
        "STRICT_PAIR_INTEGRITY = RUN_CONFIG['STRICT_PAIR_INTEGRITY']\n",
        "REMOVE_INTERBLOCK_GAPS = RUN_CONFIG['REMOVE_INTERBLOCK_GAPS']\n",
        "FORCE_RECOMPUTE_VOXELS = RUN_CONFIG['FORCE_RECOMPUTE_VOXELS']\n",
        "FORCE_RECOMPUTE_HCR_WARP = RUN_CONFIG['FORCE_RECOMPUTE_HCR_WARP']\n",
        "RECOMPUTE_WARP = RUN_CONFIG['RECOMPUTE_WARP']\n",
        "RECOMPUTE_FILTER_STATS = RUN_CONFIG['RECOMPUTE_FILTER_STATS']\n",
        "RECOMPUTE_INTENSITY_WARP = RUN_CONFIG['RECOMPUTE_INTENSITY_WARP']\n",
        "RECOMPUTE_CONF_FUNC_PAIRS = RUN_CONFIG['RECOMPUTE_CONF_FUNC_PAIRS']\n",
        "RECOMPUTE_SUITE2P_TRACE_EXPORT = RUN_CONFIG['RECOMPUTE_SUITE2P_TRACE_EXPORT']\n",
        "RECOMPUTE_FUNC_WARP_EXPORT = RUN_CONFIG['RECOMPUTE_FUNC_WARP_EXPORT']\n",
        "EXPORT_BEST_ROUND_LABELS_TO_RBEST = RUN_CONFIG['EXPORT_BEST_ROUND_LABELS_TO_RBEST']\n",
        "HCR_WARP_SPLIT_CONNECTED_COMPONENTS = RUN_CONFIG['HCR_WARP_SPLIT_CONNECTED_COMPONENTS']\n",
        "HCR_WARP_COMPONENT_CONNECTIVITY = RUN_CONFIG['HCR_WARP_COMPONENT_CONNECTIVITY']\n",
        "HCR_WARP_MIN_COMPONENT_VOXELS = RUN_CONFIG['HCR_WARP_MIN_COMPONENT_VOXELS']\n",
        "HCR_WARP_MIN_COMPONENT_VOLUME_UM3 = RUN_CONFIG['HCR_WARP_MIN_COMPONENT_VOLUME_UM3']\n",
        "HCR_WARP_DROP_LOW_Q = RUN_CONFIG['HCR_WARP_DROP_LOW_Q']\n",
        "HCR_WARP_LOW_FILTER_METRIC = RUN_CONFIG['HCR_WARP_LOW_FILTER_METRIC']\n",
        "HCR_WARP_FLAG_HIGH_Q = RUN_CONFIG['HCR_WARP_FLAG_HIGH_Q']\n",
        "HCR_WARP_HIGH_FILTER_METRIC = RUN_CONFIG['HCR_WARP_HIGH_FILTER_METRIC']\n",
        "CONF_FUNC_CSV_ANALYSIS = RUN_CONFIG['CONF_FUNC_CSV_ANALYSIS']\n",
        "GENE_ORDER = list(RUN_CONFIG['GENE_ORDER'])\n",
        "GENE_COLORS = dict(RUN_CONFIG['GENE_COLORS'])\n",
        "print('[config] RUN_CONFIG loaded with keys:', ', '.join(sorted(RUN_CONFIG.keys())))\n",
    ],
    "# [4c]": [
        "# [4c]\n",
        "import pandas as pd\n",
        "from codeants_2pf_hcr import build_fish_state_audit_df\n",
        "\n",
        "AUDIT_STRICT = True\n",
        "canonical_checks = {\n",
        "    'STATE_FISH_ID': STATE_FISH_ID,\n",
        "    'FISH_DIR': FISH_DIR,\n",
        "    'OUTDIR': OUTDIR,\n",
        "    'OUT_REG': OUT_REG,\n",
        "    'OUT_QA': OUT_QA,\n",
        "    'OUT_DERIVED': OUT_DERIVED,\n",
        "    'MATCHING_METADATA_CSV': MATCHING_METADATA_CSV,\n",
        "}\n",
        "expected_paths = {\n",
        "    'ANAT_SEG_SOURCE_PATH': {'expected': Path(str(ANAT_STACK_PATH)) if 'ANAT_STACK_PATH' in globals() and ANAT_STACK_PATH is not None else None, 'current': globals().get('ANAT_SEG_SOURCE_PATH')},\n",
        "    'ANAT_SEG_OUT_DIR': {'expected': ANALYSIS_DIR / 'structural' / 'cp_masks', 'current': globals().get('ANAT_SEG_OUT_DIR')},\n",
        "    'ANAT_SEG_CONVERT_DIR': {'expected': ANALYSIS_DIR / 'structural' / 'raw' / 'converted_nrrd_to_tif', 'current': globals().get('ANAT_SEG_CONVERT_DIR')},\n",
        "}\n",
        "fish_audit_df = build_fish_state_audit_df(\n",
        "    fish_id=FISH_ID,\n",
        "    state_fish_id=STATE_FISH_ID,\n",
        "    canonical_checks=canonical_checks,\n",
        "    expected_paths=expected_paths,\n",
        ")\n",
        "n_fail = int((fish_audit_df['status'] == 'fail').sum()) if not fish_audit_df.empty else 0\n",
        "n_warn = int((fish_audit_df['status'] == 'warn').sum()) if not fish_audit_df.empty else 0\n",
        "print(f'[fish-audit] fish={FISH_ID} fail={n_fail} warn={n_warn}')\n",
        "display(fish_audit_df)\n",
        "if AUDIT_STRICT and n_fail > 0:\n",
        "    raise RuntimeError(f'[fish-audit] failed with {n_fail} issue(s). Resolve rows with status=\\'fail\\'.')\n",
    ],
    "# [6]": [
        "# [6]\n",
        "from codeants_2pf_hcr import (\n",
        "    _find_embedded_nrrd_header,\n",
        "    _ensure_uint_labels,\n",
        "    _infer_voxels_from_open_tiff,\n",
        "    _infer_voxels_nrrd,\n",
        "    _parse_nrrd_header_text,\n",
        "    _res_to_um_per_px,\n",
        "    _to_um,\n",
        "    apply_func_orientation,\n",
        "    best_z_by_ncc,\n",
        "    corrcoef_img,\n",
        "    imread_any,\n",
        "    infer_voxels_tiff,\n",
        "    local_unsharp,\n",
        "    load_or_cache_voxels,\n",
        "    norm01,\n",
        "    top_correlated_mean,\n",
        "    zproject_mean,\n",
        ")\n",
        "\n",
        "def _apply_func_orientation(arr):\n",
        "    return apply_func_orientation(arr, polarity=POLARITY, flip_x=True)\n",
    ],
    "# [55]": [
        "# [55]\n",
        "from pathlib import Path\n",
        "from codeants_2pf_hcr import StimulusConfig, resolve_stimulus_context\n",
        "\n",
        "EXPERIMENT_LOG_CSV = None\n",
        "EXPERIMENT_META_CSV = None\n",
        "FRAME_RATE = None\n",
        "STIM_DEBUG_SOURCES = True\n",
        "STIM_TIME_SCALE = 1.0\n",
        "MEASURE_START_BLOCK = 1\n",
        "MEASURE_START_EVENT = 'start'\n",
        "REMOVE_INTERBLOCK_GAPS = True\n",
        "\n",
        "stim_ctx = resolve_stimulus_context(\n",
        "    fish_dir=FISH_DIR,\n",
        "    fish_id=FISH_ID,\n",
        "    experiment_log_csv=EXPERIMENT_LOG_CSV,\n",
        "    experiment_meta_csv=EXPERIMENT_META_CSV,\n",
        "    frame_rate=FRAME_RATE,\n",
        "    config=StimulusConfig(\n",
        "        stim_time_scale=STIM_TIME_SCALE,\n",
        "        measure_start_block=MEASURE_START_BLOCK,\n",
        "        measure_start_event=MEASURE_START_EVENT,\n",
        "        remove_interblock_gaps=REMOVE_INTERBLOCK_GAPS,\n",
        "        onset_delay_sec=STIM_ONSET_DELAY_SEC,\n",
        "    ),\n",
        ")\n",
        "FRAME_RATE = stim_ctx['frame_rate']\n",
        "df_evt = stim_ctx['df_evt']\n",
        "df_stim = stim_ctx['df_stim']\n",
        "log_path = stim_ctx['log_path']\n",
        "meta_path = stim_ctx['meta_path']\n",
        "if STIM_DEBUG_SOURCES:\n",
        "    display(stim_ctx['source_table'])\n",
        "print(f'[stim] loaded experiment log: {log_path} (rows={len(df_evt)})')\n",
        "if FRAME_RATE is not None:\n",
        "    print(f'[stim] loaded framerate: {FRAME_RATE} Hz from {meta_path}')\n",
    ],
}


def replace_cells() -> None:
    notebook = json.loads(NB_PATH.read_text())
    for cell in notebook["cells"]:
        if cell.get("cell_type") != "code":
            continue
        source = cell.get("source", [])
        if not source:
            continue
        first_line = source[0].strip()
        replacement = REPLACEMENTS.get(first_line)
        if replacement is not None:
            cell["source"] = replacement
    NB_PATH.write_text(json.dumps(notebook, indent=1))


if __name__ == "__main__":
    replace_cells()
